<!-- Image Map Generated by http://www.image-map.net/ -->

<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="{{url("/public/image/")}}/human-image.png" usemap="#image-map">

<map name="image-map">
    <area name="trigemial_ophthaimic_division" data-value="1" target="_self" alt="Trigemial-Ophthaimic division" title="Trigemial-Ophthaimic division" href="" coords="295,85,292,79,282,73,279,59,276,47,271,37,272,26,281,22,289,18,296,19,296,26,297,35,297,45,297,54,295,63,296,72" shape="poly">
    <area name="trigemial_maxillary_division" data-value="2" target="_self" alt="Trigemial-Maxillary division" title="Trigemial-Maxillary division" href="" coords="295,97,281,93,274,75,262,64,261,45,267,31,274,45,282,68,291,74,295,87"  shape="poly">
    <area name="trigemial_mandbular_division" data-value="3" target="_self" alt="Trigemial-Mandbular division" title="Trigemial-Mandbular division" href="" coords="257,74,257,63,270,70,283,91,296,95,296,117,284,114,278,97,268,82" shape="poly">
    <area name="trigemial_greater_aunicular_C2_C3" data-value="4" target="_self" alt="Trigemial-Greater aunicular C2,C3" title="Trigemial-Greater aunicular C2,C3" href="" coords="284,112,277,95,267,78,258,74,267,93,276,108" shape="poly">
    <area name="v_cranial" data-value="5" target="_self" alt="V cranial" title="V cranial" href="" coords="313,109,317,92,323,81,329,72,331,48,330,59,329,34,318,22,305,18,297,19,297,34,297,67,297,115,305,115" shape="poly">
    <area name="c2" data-value="6" target="_self" alt="C2" title="C2" href="" coords="316,106,316,92,322,84,328,76,331,68,336,63,338,69,338,77,335,84,329,91,323,97" shape="poly">
    <area name="cervical_plexus_superficial_branches" data-value="7" target="_self" alt="Cervical plexus superficial branches" title="Cervical plexus superficial branches" href="" coords="294,118,284,115,276,109,270,113,271,123,265,132,251,137,236,142,224,145,212,153,204,161,198,174,197,186,208,181,224,176,239,173,253,174,268,174,282,174,291,174,297,173,296,162,296,153,296,141,295,133,294,125" shape="poly">
    <area name="D2_D11_lateral_cutaneous" data-value="8" target="_self" alt="Intercostal nerves D2-D11-Lateral Cutaneous br." title="Intercostal nerves D2-D11-Lateral Cutaneous br." href="" coords="225,179,243,178,251,221,258,261,260,291,255,339,252,351,245,350,239,354,232,368,232,342,236,320,235,302,240,281,235,244,235,232,221,192" shape="poly">
    <area name="D2_D11_anterior_cutaneous" data-value="9" target="_self" alt="Intercostal nerves D2-D11-Anterior Cutaneous br." title="Intercostal nerves D2-D11-Anterior Cutaneous br." href="" coords="297,179,296,241,297,299,296,363,297,377,269,369,253,352,260,291,253,239,247,196,244,178" shape="poly">
    <area name="brachial_plexus_axillary" data-value="10" target="_self" alt="Brachial plexus-Axillary" title="Brachial plexus-Axillary" href="" coords="210,247,201,231,197,211,197,189,222,178,220,192,218,208,214,219,212,232,211,238" shape="poly">
    <area name="brachial_plexus_intercostobrachial" data-value="11" target="_self" alt="Brachial plexus-Intercostobrachial" title="Brachial plexus-Intercostobrachial" href="" coords="231,217,236,228,225,267,222,291,218,275,222,246" shape="poly">
    <area name="brachial_plexus_medial_cutaneous" data-value="12" target="_self" alt="Brachial plexus-Medial cutaneous" title="Brachial plexus-Medial cutaneous" href="" coords="180,395,168,393,199,310,211,247,220,192,231,216,221,259,218,278,221,295,197,353" shape="poly">
    <area name="brachial_plexus_muscutaneous" data-value="13" target="_self" alt="Brachial plexus-Muscutaneous" title="Brachial plexus-Muscutaneous" href="" coords="168,392,160,388,168,376,166,359,172,327,178,297,192,277,199,258,205,236,210,255,201,292,194,322,186,342" shape="poly">
    <area name="brachial_plexus_posterior_cutaneous" data-value="14" target="_self" alt="Brachial plexus-Radial Posterior cutaneous" title="Brachial plexus-Radial Posterior cutaneous" href="" coords="178,295,189,282,198,262,204,238,197,217,193,227,191,242,188,264,187,273" shape="poly">
    <area name="brachial_plexus_radial_superficial_branch" data-value="15" target="_self" alt="Brachial plexus-Radial Superficial branch" title="Brachial plexus-Radial Superficial branch" href="" coords="166,358,168,371,164,386,152,395,137,401,139,392,150,387,160,375" shape="poly">
    <area name="brachial_plexus_median" data-value="16" target="_self" alt="Brachial plexus-Median" title="Brachial plexus-Median" href="" coords="114,416,135,401,163,390,168,397,150,462,154,434,140,464,143,433,129,457,141,413,129,417" shape="poly">
    <area name="brachial_plexus_ulnar" data-value="17" target="_self" alt="Brachial plexus-Ulnar" title="Brachial plexus-Ulnar" href="" coords="153,461,162,425,169,394,179,395,180,409,172,432,164,456,164,434" shape="poly">
</map>

<script src="{{url('/')}}/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="{{url('/')}}/assets/js/jquery.imagemapster.js" type="text/javascript"></script>
<script  src="jquery.imagemapster.js" ></script>
<script>
    $(document).ready(function () {
        var image = $('img');
        image.mapster(
            {
                fillOpacity: 0.4,
                fillColor: "d42e16",
                strokeColor: "3320FF",
                strokeOpacity: 0.8,
                strokeWidth: 4,
                stroke: true,
                isSelectable: true,
                singleSelect: true,
                mapKey: 'name',
                listKey: 'name',
                onClick: function (e) {
                    alert(e.key);
                   // alert($(this).attr('data-value'));
                    //var newToolTip = defaultDipTooltip;
                   // $('#selections').html(xref[e.key]);
                   /* if (e.key==='asparagus') {
                        newToolTip = "OK. I know I have come down on the dip before, but let's be real. Raw asparagus without any of that " +
                            "delicious ranch and onion dressing slathered all over it is not so good.";
                    }*/
                   /* image.mapster('set_options',{areas: [{
                            key: "dip",
                            toolTip: newToolTip
                        }]
                    });*/
                },
                showToolTip: true,
                toolTipClose: ["tooltip-click", "area-click"],
                areas: [
                    {
                        key: "trigemial_ophthaimic_division",
                        fillColor: "000000",

                    },
                    {
                        key: "trigemial_maxillary_division",
                        fillColor: "000000",

                    },
                    {
                        key: "trigemial_mandbular_division",
                        fillColor: "000000",

                    },
                    {
                        key: "trigemial_greater_aunicular_C2_C3",
                        fillColor: "000000",

                    },
                    {
                        key: "v_cranial",
                        fillColor: "000000",

                    },
                    {
                        key: "c2",
                        fillColor: "000000",

                    },
                    {
                        key: "cervical_plexus_superficial_branches",
                        fillColor: "000000",

                    },
                    {
                        key: "D2_D11_lateral_cutaneous",
                        fillColor: "000000",

                    },
                    {
                        key: "D2_D11_anterior_cutaneous",
                        fillColor: "000000",

                    },
                    {
                        key: "brachial_plexus_axillary",
                        fillColor: "000000",

                    },
                    {
                        key: "brachial_plexus_intercostobrachial",
                        fillColor: "000000",

                    },
                    {
                        key: "brachial_plexus_medial_cutaneous",
                        fillColor: "000000",

                    },
                    {
                        key: "brachial_plexus_muscutaneous",
                        fillColor: "000000",

                    },
                    {
                        key: "brachial_plexus_posterior_cutaneous",
                        fillColor: "000000",

                    },
                    {
                        key: "brachial_plexus_radial_superficial_branch",
                        fillColor: "000000",

                    },
                    {
                        key: "brachial_plexus_median",
                        fillColor: "000000",

                    },
                    {
                        key: "brachial_plexus_ulnar",
                        fillColor: "000000"
                    },

                ]
            });
    });
</script>